sudo: required

language: scala

scala:
- 2.11.12
- 2.12.13
- 2.13.6

jdk:
- openjdk8

before_script:
- sudo chmod +x /usr/local/bin/sbt

after_success:
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
